server:
  port: 9000
spring:
  security:
    user:
      name: user
      password: pass
  application:
    name: spring-datarest-server
  datasource:
    url: jdbc:sqlserver://DESKTOP-HSQDKL8:1433;databaseName=springbootdb;trustServerCertificate=true
    username: user
    password: pass
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

logging:
  file:
    name: /CS544/Logging/${spring.application.name}/logs
